dist: trusty
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install: cd app && python setup.py install
script: make coverage # we're in app/ already
cache:
  directories:
    - /home/travis/virtualenv/
