version: '2'
services:
  sphinx:
    build:
      context: sphinx
    command: "searchd --nodetach --config /opt/sphinx.conf"
    ports:
    - "127.0.0.1:36307:36307"
    volumes:
    - ./sphinx/data:/opt/sphinx/index
    logging:
      driver: syslog
      options:
        tag: sphinx
    hostname: sphinx-docker
  # caching layer
  redis:
    build:
      context: redis3
    volumes:
      - ./redis3/data:/opt/redis
    logging:
      driver: syslog
      options:
        tag: redis
    hostname: redis-docker
  # Flask app
  app:
    build:
      context: app
    command: "gunicorn wbc:app -b 0.0.0.0:8080 --access-logfile -"
    environment:
      GIT_HASH: "${GIT_HASH}"
    links:
    - sphinx
    - redis
    logging:
      driver: syslog
      options:
        tag: app
    hostname: "app-docker-${HOST}"
  # nginx proxy
  nginx:
    build:
      context: nginx
    command: "nginx -g 'daemon off;'"
    ports:
    - "80:80"
    links:
    - app
    logging:
      driver: syslog
      options:
        tag: nginx
    hostname: "nginx-docker-${HOST}"
