version: '2.4'
services:
  sphinx:
    build:
      context: sphinx
    ports:
    - "127.0.0.1:36307:36307" # bind to local interface only!
    volumes:
    - ./sphinx/data:/opt/sphinx/index
    - ./sphinx/sphinx.conf:/opt/sphinx/conf/sphinx.conf
    mem_limit: 512m # match indexer.value from sphinx.conf
    logging:
      driver: syslog
      options:
        tag: wbc-sphinx
    hostname: sphinx-docker
  # Flask app
  app:
    build:
      context: app
    command: "gunicorn wbc:app -b 0.0.0.0:8080 --access-logfile -"
    ports:
    - "127.0.0.1:8080:8080" # bind a local interface only!
    volumes:
    - ./app/sitemap:/opt/app/wbc/sitemap
    environment:
      GIT_HASH: "${GIT_HASH}"
    logging:
      driver: syslog
      options:
        tag: wbc-app
    hostname: "app-docker-${HOST}"
  # nginx proxy
  nginx:
    # https://hub.docker.com/r/macbre/nginx-brotli
    image: macbre/nginx-brotli:1.18.0
    volumes:
      # mount cache directory
      - ./nginx/cache:/var/nginx/cache
      # mount SSL certificate files
      - ./nginx/fullchain.cer:/etc/nginx/cert/fullchain.cer
      - ./nginx/wbc.macbre.net.key:/etc/nginx/cert/wbc.macbre.net.key
      # mount site config
      - ./nginx/site.conf:/etc/nginx/conf.d/wbc.conf:ro
      # common config files
      - ./nginx/caching.conf:/etc/nginx/conf.d/caching.conf:ro
    ports:
    - "${NGINX_HTTP_PORT}:81"
    - "443:443"
    logging:
      driver: syslog
      options:
        tag: wbc-nginx
    hostname: "nginx-docker-${HOST}"
    depends_on:
    - app
    - sphinx
    restart: always
    healthcheck:
      # wget -q 0.0.0.0:80/.well-known/acme-challenge/foo -O -
      test: ["CMD", "wget", "0.0.0.0:81/.well-known/acme-challenge/foo", "-q", "-O" ,"-", "-U", "wget/heathcheck"]
      interval: 15s
      timeout: 1s
      retries: 3
