version: '2'
services:
  sphinx:
    build:
      context: sphinx
    command: "searchd --nodetach --config /opt/sphinx.conf"
    ports:
    - "36307:36307"
    volumes:
    - ./sphinx/data:/opt/sphinx/index
    logging:
      driver: syslog
      options:
        tag: sphinx
    hostname: sphinx-docker
