version: '2'
services:
  sphinx:
    build:
      context: sphinx
    command: "searchd --nodetach --config /opt/sphinx.conf"
    ports:
    - "36307:36307"
    volumes:
    - ./sphinx/data:/opt/sphinx/index
    logging:
      driver: syslog
      options:
        tag: sphinx
    hostname: sphinx-docker
  # caching layer
  redis:
    build:
      context: redis3
    volumes:
      - ./redis3/data:/opt/redis
    logging:
      driver: syslog
      options:
        tag: redis
    hostname: redis-docker
  # Flask app
  app:
    build:
      context: app
    command: "server"
    ports:
    - "8080:8080"
    links:
    - sphinx
    - redis
    logging:
      driver: syslog
      options:
        tag: app
    hostname: app-docker
